typography_spectrum: 0.9713818202726543
color:
  brandStrength: 0.029486082261428237
  lightness: 0.7913009007461369
  saturation: 0.9719148690346628
  rhythmicContrast: 0.729191665770486
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
layout_spectrum: 0.5344911573920399
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/f630297c-3caa-4846-ac1b-42f84fd25ccd.png
name: ixloc.tv
navigation:
  - id: 'https://www.twitch.tv/ixloc'
    url: 'https://www.twitch.tv/ixloc'
    name: My Twitch
    type: external
title: ''
